package:
  name: vale
  version: "3.12.0"
  epoch: 0
  description: "A markup-aware linter for prose built with speed and extensibility in mind"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/errata-ai/vale
      tag: v${{package.version}}
      expected-commit: 44c18b3d2ebc971c160cec26cd179a3f73d37f58

  - uses: go/build
    with:
      packages: ./cmd/vale
      output: vale
      ldflags: -X main.version=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: errata-ai/vale
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - name: Test Vale installation
      runs: |
        vale --version
        vale --help
    - name: Basic linting test
      runs: |
        mkdir -p /tmp/vale-test
        cat > /tmp/vale-test/test.md << 'EOF'
        # Test Document

        This is a test document with some issues. This sentence is very long and contains many words that make it difficult to read and understand for most readers.

        The quick brown fox jumps over the lazy dog. This sentence uses passive voice and should be fixed.
        EOF

        cat > /tmp/vale-test/.vale.ini << 'EOF'
        StylesPath = .
        MinAlertLevel = suggestion

        [*.md]
        BasedOnStyles = Vale
        EOF

        cd /tmp/vale-test
        vale test.md || echo "Vale executed successfully"
    - name: Test version output format
      runs: |
        vale --version | grep -q "${{package.version}}"
